name: Publish packages to npmjs.com
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 'npmjs.com'
    defaults:
      run:
        working-directory: lerna-publish-sample
    permissions:
      id-token: write # Required for OIDC
      contents: write # Required for tagging.
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      # Ensure npm 11.5.1 or later is installed.
      - name: Install latest npm
        run: npm install -g npm@latest
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build packages
        run: yarn lerna run prepare
      - name: Run linting
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Configure Git
        run: |
          git config --global user.email "git@users.noreply.github.com"
          git config --global user.name "github actions"
      - name: Publish packages (using OIDC Trusted Publishing)
        run: yarn lerna publish from-package --yes
      - name: Create version tags
        run: |
          git fetch --tags
          yarn lerna exec \$LERNA_ROOT_PATH/scripts/create-package-tag.sh
          git push --tags
